---
title: "Case Study 09"
author: Logan Hales
date: August 1, 2020
output: github_document
---
```{r}
library(sf)
library(tidyverse)
library(ggmap)
library(spData)
library(lubridate)
data(world)
data(us_states)

# Download a csv from noaa with storm track information
dataurl="https://www.ncei.noaa.gov/data/international-best-track-archive-for-climate-stewardship-ibtracs/v04r01/access/csv/ibtracs.NA.list.v04r01.csv"

storm_data <- read_csv(dataurl)
```
 
```{r}
storm_data_new <- storm_data%>%
  mutate(year = year(ISO_TIME))%>%
  filter(year >= 1950) %>%
  mutate_if(is.numeric, function(x) ifelse(x==-999.0,NA,x)) %>%
  mutate(decade=(floor(year/10)*10))


sf_storm_data <- storm_data_new %>%
  st_as_sf(coords=c("LON","LAT"),crs=4326, remove = FALSE)

region <- st_bbox(sf_storm_data)
```
 
```{r}
ggplot(data = world)+
  geom_sf()+
  stat_bin2d(data=storm_data_new, aes(y=st_coordinates(sf_storm_data)[,2], x=st_coordinates(sf_storm_data)[,1]),bins=100)+
  facet_wrap(~decade)+
  scale_fill_distiller(palette="YlOrRd", trans="log", direction=-1, breaks = c(1,10,100,1000))+
  coord_sf(ylim=region[c(2,4)], xlim=region[c(1,3)])
```
 
```{r}

st_us_states <- st_as_sf(us_states)
st_us_states_new <- st_transform(st_us_states, st_crs(sf_storm_data))

us_states_name <- st_us_states_new%>%
  select(state = NAME)

storm_states <- st_join(sf_storm_data, us_states_name, join = st_intersects,left = F)%>%
  group_by(state)%>%
  summarize(storms=length(unique(NAME)))%>%
  arrange(desc(storms))%>%
  slice(1:5)
```
 
 