---
title: "Case Study 11"
author: Your Name
date: August 1, 2020
output: github_document
---
```{r}
library(tidyverse)
library(spData)
library(sf)

## New Packages
library(mapview) # new package that makes easy leaflet maps
library(foreach)
library(doParallel)
registerDoParallel(4)
getDoParWorkers() # check registered cores

```


```{r}
# go to  http://api.census.gov/data/key_signup.html and get a key, then run the line below with your key.  Don't push your key to github!
library(tidycensus)
census_api_key("21135f12ab11f122bd58c82512cd56c77b9cc064")
```
 
```{r}
library(tidycensus)
race_vars <- c(
  "Total Population" = "P1_001N",
  "White alone" = "P1_003N",
  "Black or African American alone" = "P1_004N",
  "American Indian and Alaska Native alone" = "P1_005N",
  "Asian alone" = "P1_006N",
  "Native Hawaiian and Other Pacific Islander alone" = "P1_007N",
  "Some Other Race alone" = "P1_008N",
  "Two or More Races" = "P1_009N"
)


options(tigris_use_cache = TRUE)
erie <- get_decennial(geography = "block", variables = race_vars, year=2020,
                  state = "NY", county = "Erie County", geometry = TRUE,
                  sumfile = "pl", cache_table=T) 
c(xmin=-78.9,xmax=-78.85,ymin=42.888,ymax=42.92)
```
 
```{r}
F1<- foreach(i = unique(erie$variable), .packages=c("dplyr","sf"),.combine=rbind) %do%
  {t1=filter(erie, variable == i)
    t2= st_sample(t1,size=t1$value)
    return(t2)}

F1_Conversion <- st_as_sf(F1, coords = c("x", "y"), crs = 4326) 

mutate(variables=F1_Conversion)
```


```{r}
mapview(F1_Conversion, zcol=variable)
```
 
 