---
title: "Case Study 04"
author: Logan Hales
date: September 23, 2024
output: github_document
---

## First Header

Comments

```{r}
library(tidyverse)
library(nycflights13)
airlines
airports
planes
weather
flights
#load in the necessary data to join later, and necessary library
view(dist)
str(dist)
head(dist)

view(planes)

arrange(flights)
view(flights)

 view(airports)

 flight_distance <- flights%>%
arrange(distance)
#associate flights with new data set as a means to present the distance and name columns with each other
 ?slice

flight_distance_max <- flight_distance%>%
  slice_max(distance)
#slice the maximum distance to find the airports that are the farthest apart
flight_distance_max%>%
  left_join(airports, c("dest" = "faa"))
#left join to match connect the faa and dest values to organize the largest distance 
flight_distance_max%>%
  select(dest)
#section of dest for analysis
as.character(flight_distance_max)
#needed single value
```

## Second Header

Comments

```{r}
plot(pressure)

```
